### ISSUE TITLE
混淆是存在一定缺陷

### ISSUE THREAD

**Issue by LimeVista** [Blankj/FreeProGuard#10]
[ARouter#L12](https://github.com/Blankj/FreeProGuard/blob/master/free-proguard/proguard-ARouter.pro#L12)
[ButterKnife#L10](https://github.com/Blankj/FreeProGuard/blob/master/free-proguard/proguard-ButterKnife.pro#L10)
这两行规则会导致混淆缺陷，使得所有公开类类名无法被混淆，干扰混淆器对与之无关的类内联优化。
![保留以上两行时](https://user-images.githubusercontent.com/18542751/54907919-ac047880-4f21-11e9-89d4-a42af78ff5ce.png)
![注释以上两行时](https://user-images.githubusercontent.com/18542751/54907957-bf174880-4f21-11e9-8ef3-b61985edb783.png)
[测试样例](https://github.com/Blankj/FreeProGuard/files/3002425/test_001-master.zip)

**Comment by Blankj** [comment]
好啦，发布 1.0.0 版本了，多谢反馈哈
