### ISSUE TITLE
在3.5.2android studio 版本上混淆问题

### ISSUE THREAD

**Issue by gegeName** [Blankj/FreeProGuard#12]
首先谢谢你的库，节省我了我的一堆混淆规则，但是你的混淆规则中greenDao中没有加上-keep class **$Properties {*;}这一条导致在android studio 3.5.2版本中混淆Greendao不正确，导致出错。希望你补上上面那条混淆规则，谢谢了。

**Comment by Blankj** [comment]
使用 1.0.2 即可
