### ISSUE TITLE
提个意见，可能gradle插件是实现这个功能比较合适的选择

### ISSUE THREAD

**Issue by lonelyleaf** [Blankj/FreeProGuard#3]
做成gradle插件可以分析项目的依赖，再根据依赖的信息去动态生成模板，或者加载对应的混淆文件比较合适。

现在这种只是把各个库的混淆规则全部塞到一起，不够优雅，也有潜在bug的可能

**Comment by Blankj** [comment]
多添加防混淆规则进来最终用不到其实也不会出现什么 bug，至于耗时也是微乎其微的，如果要打造更得更精品，插件就是一个很好的选择了哈，不过就是加重了我这边的开发量，后续可以考虑，感谢提议。
